"""AION2 查询插件的核心层。"""

from . import events, kinah
from .client import Aion2Client, RateLimiter, decode_character_id
from .errors import (
    Aion2Error,
    BadRequest,
    FeatureUnavailable,
    NetworkError,
    NoSeason,
    NotFound,
    RateLimited,
    UpstreamError,
)
from .models import (
    Character,
    CharacterRef,
    CharacterSummary,
    DaevanionSummary,
    Equipment,
    EquipSlot,
    GameClass,
    Item,
    Page,
    Post,
    PostBody,
    Profile,
    Server,
    Skill,
    Stat,
    TitleSummary,
    clean_text,
)
from .routes import BOARDS, GLOSSARY_REGION, RANKING_LABELS, REGIONS, Routes, region_of
from . import settings

__all__ = [
    "Aion2Client",
    "Aion2Error",
    "BOARDS",
    "BadRequest",
    "Character",
    "CharacterRef",
    "CharacterSummary",
    "DaevanionSummary",
    "Equipment",
    "EquipSlot",
    "FeatureUnavailable",
    "GLOSSARY_REGION",
    "GameClass",
    "Item",
    "NetworkError",
    "NoSeason",
    "NotFound",
    "Page",
    "Post",
    "PostBody",
    "Profile",
    "RANKING_LABELS",
    "REGIONS",
    "RateLimited",
    "RateLimiter",
    "Routes",
    "Server",
    "Skill",
    "Stat",
    "TitleSummary",
    "UpstreamError",
    "clean_text",
    "decode_character_id",
    "events",
    "kinah",
    "region_of",
    "settings",
]
